### ISSUE TITLE
 https://bootstrap.pypa.io/get-pip.py needs to be updated to https://bootstrap.pypa.io/3.5/get-pip.py 

### ISSUE THREAD

**Issue by kristoforerickson** [CircleCI-Public/aws-elastic-beanstalk-orb#7]
## Orb version:
1.0.0

## What happened:

Setting up python3-setuptools (33.1.1-1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  17.1M      0 --:--:-- --:--:-- --:--:-- 17.3M
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmpdc43l8e8/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

## Expected behavior:

No Error

## Additional Information:

https://bootstrap.pypa.io/get-pip.py this package has a breaking change for Python 3.5 as of this weekend, they created a fix but this URL now has to be updated to https://bootstrap.pypa.io/3.5/get-pip.py. Please see issue here - https://github.com/pypa/get-pip/issues/83

**Comment by gmemstr** [comment]
Waiting for CPE team to have relevant permissions to address this - do have a local branch with the fix.

**Comment by kristoforerickson** [comment]
@gmemstr Thanks - it will be nice to be able to build again :)

**Comment by kristoforerickson** [comment]
@gmemstr do you know when this will be published?

**Comment by gmemstr** [comment]
@kristoforerickson Sorry for not following up, missed my notifications - this fix is in orb version 1.0.1 :)
